#import from "../fragments/ProfFragment.gql"

query AllProfs {
  profs {
    ...ProfFragment
  }
}

query SingleProfByMatricule($profMatricule: String!) {
  profByMatricule(profMatricule: $profMatricule) {
    ...ProfFragment
  }
}
